### ISSUE TITLE
Update CUDATOOLKIT in external module

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#11]
On Santis we have as default cudatoolkit/7.5.18-1.0502.10743.2.1

It needs to be included in the list: /apps/common/easybuild/cray_external_modules_metadata.cfg

[cudatoolkit/7.5.18-1.0502.10743.2.1]
name = CUDA
version = 7.5.18-1.0502.10743.2.1
prefix = CRAY_CUDATOOLKIT_DIR

**Comment by gppezzi** [comment]
fixed
