### ISSUE TITLE
Easyconfig for LAMMPS (Cuda) on the Cray XC30

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#23]
Hi recall reading a development Easyconfig file for LAMMPS on the EasyBuild mailing list some time ago, but I could not find it on the EasyBuild/easyconfig development repository.

As we support LAMMPS with Cuda on the XC30, we should try to implement a recipe. Curently I do the following to build LAMMPS, after downloading the tarball from http://lammps.sandia.gov:
$ module swap PrgEnv-cray PrgEnv-gnu
$ module load fftw
$ module load cudatoolkit
$ tar xzvf lammps.tar.gz
Apply patch.XXYYYZZ on top folder in lammps (README,LICENSE) if any
$ patch -bp1 < patch.XXYYYZZ
$ make package-update
$ make yes-standard yes-gpu yes-user-reaxc yes-user-omp
$ make no-voronoi no-reax no-poems no-meam no-kim

Change to subfolder ../lib/gpu
cp /project/csstaff/lucamar/install_scripts/lammps/xc30/Makefile_gnu-gpu.xc30 .
make -f Makefile_gnu-gpu.xc30

Change to subfolder ./src
cp /project/csstaff/lucamar/install_scripts/lammps/xc30/Makefile-gnu.xc30 MAKE/Makefile.xc30
make xc30
The executable lmp_xc30 should be created at the end of the compilation proces

**Comment by boegel** [comment]
easyblock PRs:
* https://github.com/hpcugent/easybuild-easyblocks/pull/594
* https://github.com/hpcugent/easybuild-easyblocks/pull/833
easyconfig PRs:
* https://github.com/hpcugent/easybuild-easyconfigs/pull/1559
* https://github.com/hpcugent/easybuild-easyconfigs/pull/1782
* https://github.com/hpcugent/easybuild-easyconfigs/issues/2511

some help in getting these synced/merged is much appreciated...

**Comment by gppezzi** [comment]
New eb file is [here](https://github.com/eth-cscs/tools/blob/master/easybuild/easyconfigs/l/LAMMPS/LAMMPS-14May16-CrayGNU-2016.03.eb).

Thanks @lucamar
