### ISSUE TITLE
Update CSCS EB recipes for the Cray stable support

### ISSUE THREAD

**Issue by gppezzi** [eth-cscs/tools#3]
# Piz Daint & Piz Dora

Piz Daint and Dora from now on should have a common software stack (except for the GPU-enabled software). 

Please update the list as the new .eb files are ready and post your remarks as comments.

- [x] ~~Boost/1.59.0-CrayGNU-2015.11-Python-2.X~~ 
- [x] Boost/1.60.0-CrayGNU-2015.11-Python-2.7.11 (https://github.com/hpcugent/easybuild-easyconfigs/pull/2615)
- [x] CDO/1.7.1-CrayGNU-2015.11
- [x] CMake/3.2.2-CrayGNU-2015.11 -> CMake/3.5.0
- [x] GMP/6.1.0
- [x] ~~HDF5/1.8.11-CrayGNU-2015.11-serial~~ (module hidden and won't be reinstalled)
- [x] Python/2.7.9-CrayGNU-2015.11 (https://github.com/hpcugent/easybuild-easyconfigs/pull/2608)
- [x] Python/2.7.10-CrayGNU-2015.11 (https://github.com/hpcugent/easybuild-easyconfigs/pull/2608)
- [x] Python/3.4.3 -> Python/3.5.1-CrayGNU-2015.11
- [x] ZeroMQ/4.1.3 (hidden)
- [x] git/2.7.2 (dummy/non-cray)
- [x] h5py/2.5.0-CrayGNU-2015.11-Python-2.X-parallel (https://github.com/hpcugent/easybuild-easyconfigs/pull/2613)
- [x] h5py/2.5.0-CrayGNU-2015.11-Python-2.X-serial (https://github.com/hpcugent/easybuild-easyconfigs/pull/2613)
- [x] h5py/2.5.0-CrayGNU-2015.11-Python-3.X-parallel (https://github.com/hpcugent/easybuild-easyconfigs/pull/2613)
- [x] h5py/2.5.0-CrayGNU-2015.11-Python-3.X-serial (https://github.com/hpcugent/easybuild-easyconfigs/pull/2613)
- [x] magma/1.6.2-CrayGNU-2015.11 (or 2015.06, not sure if it works with cuda 7)
- [x] matplotlib/1.4.3-CrayGNU-2015.11-Python-2.X -> matplotlib/1.5.0-CrayGNU-2015.11-Python-3.X (PR [here](https://github.com/hpcugent/easybuild-easyconfigs/pull/2608))
- [x] ~~matplotlib/1.4.3-CrayGNU-2015.11-Python-3.X~~ -> matplotlib/1.5.0-CrayGNU-2015.11-Python-3.X
- [x] ncview/2.1.6-CrayGNU-2015.11
- [x] netcdf-python/1.1.8-CrayGNU-2015.11-Python-2.X
- [x] netcdf-python/1.1.8-CrayGNU-2015.11-Python-3.X
- [x] pycuda/2015.1-CrayGNU-2015.11-Python-2.X (daint only)
- [x] pycuda/2015.1-CrayGNU-2015.11-Python-3.X (daint only)

**Comment by gppezzi** [comment]
Concerning CMake: I propose we provide PrgEnv agnostic versions of CMake, with dummy toolchain, compiled with system gcc and, if needed, we add versions specific to a PrgEnv. 

Any thoughts?

**Comment by lucamar** [comment]
I agree, provided that the dummy toolchain version of CMake works as expected.
In my case, I still do not manage to build GROMACS with CUDA 7.0 with both CMake/3.5.0 and          CMake/3.5.0-CrayGNU-2016.03 (or earlier versions), so the failure it's likely not caused by CMake.

**Comment by gppezzi** [comment]
It seems that the list is done, all of our current production easyconfig files are ready and working with the new cray stable support.

**Comment by boegel** [comment]
@gppezzi: are PRs planned for each of these?

**Comment by gppezzi** [comment]
@boegel we can think about that for the hackathon, it would be a good exercise. 

The easyblocks probably need to be polished (and be aware that we had to skip some more sanity checks ;)
