### ISSUE TITLE
Task Force to port last SCS manual builds to EB

### ISSUE THREAD

**Issue by gppezzi** [eth-cscs/tools#4]
* To be worked on during the hackathon
* This is a raw list of modules that were manually installed and that are currently visible
  * some of them are already available with EB
  * we will update this list as we confirm that the EB modules can replace the old ones

* I made an initial task distribution (but this is just a proposal, not an obligation!)

Please write down a comment for updating/fixing this list.

# Daint + Dora

### Pending:

- [ ]  ImageMagik @gppezzi
- [ ]  atompaw @jgphpc  
- [ ]  cpmd @ajocksch 
- [ ]  ghostscript @gppezzi 
- [ ]  GROMACS GPU @lucamar  
- [ ]  namd @ChristopherBignamini 
- [ ]  ncl @vkarak  
- [ ]  netcdfsn @gppezzi
- [ ] QuantumESPRESSO @lucamar 
- [ ]  scorep @jgphpc (needs refactoring and test with 2016.03)

### Low priority/ under request:
- [ ]  plumed @lucamar (under request)
- [ ]  lammps @lucamar (low priority)
- [ ]  adios 
- [ ]  idl 

# Monte leone 
- [x] OpenFoam @ajocksch 
- [ ] foam-extend @vkarak  (to be defined if it should installed by the users)
- [ ] paraview @jfavre

### Already available / not needed:

- [x]  amber @vkarak
- [x]  ABINIT
- [x]  Boost
- [x]  cdo @gppezzi 
- [x]  CP2K
- [x]  GMP
- [x]  GROMACS (non cuda version) 
- [x]  R
- [x]  cmake
- [x]  ddt (binary, can be used from /apps/common)
- [x]  ffmpeg (to be removed on the next upgrade) 
- [x]  gsl
- [x]  iaca
- [x]  libint
- [x]  libxc
- [x]  magma
- [x]  ncview
- [x]  nco @gppezzi
- [x]  nwchem
- [x]  opengl
- [x]  paraview @jfavre
- [x]  perflite 
- [x]  perflite-base
- [x]  perftools-base 
- [x]  python 
- [x]  qt @jgphpc  
- [x]  scalasca
- [x]  slurm (hpc-ops)
- [x]  szip/2.1 
- [x]  vampir (binary, can be used from /apps/common)
- [x]  vmd (binary only, installed by 3rd party) 
- [x]  vtk @jfavre (not needed, provided by paraview)
- [x]  visit @jfavre (to be discussed)
- [x]  viz

**Comment by bcumming** [comment]
__fmpeg__ was added by me for a user (Diego Rosinelli). I made it clear that this wasn't a supported CSCS software, and that we wouldn't be responsible for it (so remove if you want). If you want, I can provide the set of dependencies that were required to build it... it took me a morning to do.

**Comment by gppezzi** [comment]
@bcumming thanks for the feedback! We're not deleting existing software, this just means that we won't be reinstalling/maintaining it ourselves for the next upgrades (since it is an individual request).

**Comment by lucamar** [comment]
I have updated the list with some codes that I've managed to build with the latest Easybuild development release available in /apps/common/tools.
