### ISSUE TITLE
Update list of External Cray modules

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#5]
EASYBUILD_EXTERNAL_MODULES_METADATA:
/apps/common/easybuild/cray_external_modules_metadata.cfg
E.g. add fftw/3.3.4.7 (default on Santis as of Cray PE 2016.03)

**Comment by gppezzi** [comment]
https://github.com/eth-cscs/tools/blob/master/easybuild/cray_external_modules_metadata.cfg#L74

**Comment by lucamar** [comment]
Thanks!
