### ISSUE TITLE
GMP-6.1.0 fails 4 tests with CrayGNU-2016.03 on Santis

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#6]
$ eb GMP-6.1.0-CrayGNU-2016.03.eb
== temporary log file in case of crash /tmp/eb-xN1T8h/easybuild-h2RRF5.log
== processing EasyBuild easyconfig /apps/common/UES/tools/easybuild/easyconfigs/g/GMP/GMP-6.1.0-CrayGNU-2016.03.eb
== building and installing GMP/6.1.0-CrayGNU-2016.03...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/lucamar/GMP/6.1.0/CrayGNU-2016.03): build failed (first 300 chars): cmd "make check" exited with exitcode 2 and output:
make  check-recursive
make[1]: Entering directory `/dev/shm/lucamar/GMP/6.1.0/CrayGNU-2016.03/gmp-6.1.0'
Making check in tests
make[2]: Entering directory `/dev/shm/lucamar/GMP/6.1.0/CrayGNU-2016.03/gmp-6.1.0/tests'
Making check in .
make[3]: Enter
== Results of the build can be found in the log file /tmp/eb-xN1T8h/easybuild-GMP-6.1.0-20160316.051734.thHwi.log
ERROR: Build of /apps/common/UES/tools/easybuild/easyconfigs/g/GMP/GMP-6.1.0-CrayGNU-2016.03.eb failed (err: 'build failed (first 300 chars): cmd "make check" exited with exitcode 2 and output:\nmake  check-recursive\nmake[1]: Entering directory `/dev/shm/lucamar/GMP/6.1.0/CrayGNU-2016.03/gmp-6.1.0\'\nMaking check in tests\nmake[2]: Entering directory `/dev/shm/lucamar/GMP/6.1.0/CrayGNU-2016.03/gmp-6.1.0/tests\'\nMaking check in .\nmake[3]: Enter')

List of tests FAILED (from logfile):
../../test-driver: line 107: 19836 Segmentation fault      "$@" > $log_file 2>&1
FAIL: t-get_d
../../test-driver: line 107: 19855 Segmentation fault      "$@" > $log_file 2>&1
FAIL: t-get_d_2exp
../../test-driver: line 107: 20064 Segmentation fault      "$@" > $log_file 2>&1
FAIL: t-divis
../../test-driver: line 107: 20197 Segmentation fault      "$@" > $log_file 2>&1
FAIL: t-cmp_d

**Comment by gppezzi** [comment]
Where did you get this GMP eb file from?

I've fixed this [here](https://github.com/hpcugent/easybuild-easyconfigs/pull/2608/commits/1e3228ddbbea445c7ace7fc6272bbb89789b2fd3), but maybe our local files were not updated yet (now it should work for 2015.11 and 2016.03).

**Comment by lucamar** [comment]
It used to work already for 2015.11 even without "toolchainopts = {'lowopt': True}", that's why I've opened this issue. See the easyconfig created after my build in my sandbox on Piz Daint with 2015.11:
/apps/daint/UES/5.2.UP04/sandbox-lm/easybuild/ebfiles_repo/GMP/GMP-6.1.0-CrayGNU-2015.11.eb
Anyway, now it works with 2016.03 on Santis as well, thanks for updating the easyconfig on our internal repository.

**Comment by gppezzi** [comment]
The tests fail if we use -O2 (which is used by default by EB) and it used to work because you were overriding CFLAGS:
```
'export CFLAGS=-mcmodel=large && '
```
Now we're extending CFLAGS and making it explicit that we want lowopt (-O1).

**Comment by boegel** [comment]
Note that this probably means that GMP was being built with `-O0` (which is the default optimisation level  for GCC, believe it or not). Not sure if the Cray wrapper do something smarter by default...
